### ISSUE TITLE
Player Class Frozen/Full Server Meltdown

### ISSUE THREAD

**Issue by Sindusk** [ago1024/WurmServerModLauncher#19]
This occurs whenever player is passed as an argument to any method, whether it's called or not. Defrosting the method simply breaks the server completely, and causes all mods to cease functioning. I've created a demonstration mod for it.

Mod source code: http://pastebin.com/qqYTzhdA (configure defrost commented out)
Error with no configure defrost: http://pastebin.com/bwZ69im4
Error when using configure defrost: http://pastebin.com/wypTtr4g
[wurmmodtemplate.zip](https://github.com/ago1024/WurmServerModLauncher/files/617880/wurmmodtemplate.zip)

**Comment by ago1024** [comment]
This is not a bug. It's a side effect of class loading.

When Java loads the class ModTemplate it has to create code for the method omgsobroken and for this it has to load the class Player. When Java loads a class through the javassist class loader it freezes the class and makes it unavailable for further bytecode changes.

The way to work around this problem is to isolate the code in a runnable. This effectively puts the code in a different class (eg. ModTemplate$1) and Java is fine with just loading the class Runnable and knowing that it can later create a Runnable from the nested class. But it does not need to load the nested class (with all the references to server classes) right away.

The method would look like this:
```
public void omgsobroken(Player p, Appointment a) {
	Runnable r = new Runnable() {
		public void run() {
			Message mess = new Message(null, (byte) 16, "Server", p.getName() + " receives the " + a.getNameForGender(p.getSex()) + " of " + Kingdoms.getNameFor(p.getKingdomId()) + "!", 0, 0, 255);
			for (Player rec : Players.getInstance().getPlayers()) {
				mess = new Message(rec, (byte) 16, "Server", p.getName() + " " + "receives the " + a.getNameForGender(p.getSex()) + " of " + Kingdoms.getNameFor(p.getKingdomId()) + "!", 0, 0, 255);
				rec.getCommunicator().sendMessage(mess);
			}
		}
	};
	r.run();
}
```
